version: '3.8'

services:
  # 1. CONTENEDOR DEL BACKEND
  backend:
    build: ./backend
    container_name: ziba_backend
    environment:
      - DB_HOST=10.207.64.75
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://localhost:3000/health || exit 1"]
      interval: 3s
      timeout: 5s
      retries: 15
      start_period: 20s

  # 2. CONTENEDOR DEL FRONTEND
  frontend:
    build: ./frontend
    container_name: ziba_frontend
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
